In [23]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [24]:
df = pd.read_csv('C:\\Users\\a\\OneDrive\\Desktop\\Predictive-Analytics-for-Customer-Churn\\data\\row\\train.csv')

# PHASE 1 — Understand the Dataset

1. How many rows and columns are present?
2. What does each row represent?
3. What does each column represent?
4. What are the column names?
5. What are the data types?
6. Which columns are numerical?
7. Which columns are categorical?
8. Which columns are dates/time?
9. What is the target variable?
10. Is the target variable classification or regression?
12. Are there duplicate rows?
13. Are there unique IDs?
14. Which columns have very high cardinality?
15. Are there unnecessary columns?
16. Is the dataset balanced?

In [26]:
df.shape

(243787, 21)

In [30]:
df.head()

,AccountAge,MonthlyCharges,TotalCharges,SubscriptionType,PaymentMethod,PaperlessBilling,ContentType,MultiDeviceAccess,DeviceRegistered,ViewingHoursPerWeek,...,ContentDownloadsPerMonth,GenrePreference,UserRating,SupportTicketsPerMonth,Gender,WatchlistSize,ParentalControl,SubtitlesEnabled,CustomerID,Churn
0,20,11.055215,221.104302,Premium,Mailed check,No,Both,No,Mobile,36.758104,...,10,Sci-Fi,2.176498,4,Male,3,No,No,CB6SXPNVZA,0
1,57,5.175208,294.986882,Basic,Credit card,Yes,Movies,No,Tablet,32.450568,...,18,Action,3.478632,8,Male,23,No,Yes,S7R2G87O09,0
2,73,12.106657,883.785952,Basic,Mailed check,Yes,Movies,No,Computer,7.395160,...,23,Fantasy,4.238824,6,Male,1,Yes,Yes,EASDC20BDT,0
3,32,7.263743,232.439774,Basic,Electronic check,No,TV Shows,No,Tablet,27.960389,...,30,Drama,4.276013,2,Male,24,Yes,Yes,NPF69NT69N,0
4,57,16.953078,966.325422,Premium,Electronic check,Yes,TV Shows,No,TV,20.083397,...,20,Comedy,3.616170,4,Female,0,No,No,4LGYPK7VOL,0

In [31]:
df.tail()

,AccountAge,MonthlyCharges,TotalCharges,SubscriptionType,PaymentMethod,PaperlessBilling,ContentType,MultiDeviceAccess,DeviceRegistered,ViewingHoursPerWeek,...,ContentDownloadsPerMonth,GenrePreference,UserRating,SupportTicketsPerMonth,Gender,WatchlistSize,ParentalControl,SubtitlesEnabled,CustomerID,Churn
243782,77,9.639902,742.272460,Basic,Mailed check,No,Movies,No,Computer,13.502729,...,47,Sci-Fi,3.697451,1,Male,8,Yes,No,FBZ38J108Z,0
243783,117,13.049257,1526.763053,Premium,Credit card,No,TV Shows,Yes,TV,24.963291,...,35,Comedy,1.449742,4,Male,20,No,No,W4AO1Y6NAI,0
243784,113,14.514569,1640.146267,Premium,Credit card,Yes,TV Shows,No,TV,10.628728,...,44,Action,4.012217,6,Male,13,Yes,Yes,0H3SWWI7IU,0
243785,7,18.140555,126.983887,Premium,Bank transfer,Yes,TV Shows,No,TV,30.466782,...,36,Fantasy,2.135789,7,Female,5,No,Yes,63SJ44RT4A,0
243786,90,11.593774,1043.439704,Premium,Mailed check,No,Both,No,TV,24.972537,...,11,Action,1.428896,3,Female,1,Yes,No,A6IN701VRY,0

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243787 entries, 0 to 243786
Data columns (total 21 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   AccountAge                243787 non-null  int64
 1   MonthlyCharges            243787 non-null  float64
 2   TotalCharges              243787 non-null  float64
 3   SubscriptionType          243787 non-null  object
 4   PaymentMethod             243787 non-null  object
 5   PaperlessBilling          243787 non-null  object
 6   ContentType               243787 non-null  object
 7   MultiDeviceAccess         243787 non-null  object
 8   DeviceRegistered          243787 non-null  object
 9   ViewingHoursPerWeek       243787 non-null  float64
 10  AverageViewingDuration    243787 non-null  float64
 11  ContentDownloadsPerMonth  243787 non-null  int64
 12  GenrePreference           243787 non-null  object
 13  UserRating                243787 non-null  float64
 14  SupportTicketsPerMonth    243787 non-null  int64
 15  Gender                    243787 non-null  object
 16  WatchlistSize             243787 non-null  int64
 17  ParentalControl           243787 non-null  object
 18  SubtitlesEnabled          243787 non-null  object
 19  CustomerID                243787 non-null  object
 20  Churn                     243787 non-null  int64
dtypes: float64(5), int64(5), object(11)
memory usage: 39.1+ MB

In [35]:
df.columns

Index(['AccountAge', 'MonthlyCharges', 'TotalCharges', 'SubscriptionType',
       'PaymentMethod', 'PaperlessBilling', 'ContentType', 'MultiDeviceAccess',
       'DeviceRegistered', 'ViewingHoursPerWeek', 'AverageViewingDuration',
       'ContentDownloadsPerMonth', 'GenrePreference', 'UserRating',
       'SupportTicketsPerMonth', 'Gender', 'WatchlistSize', 'ParentalControl',
       'SubtitlesEnabled', 'CustomerID', 'Churn'],
      dtype='object')

In [36]:
df.dtypes

AccountAge                    int64
MonthlyCharges              float64
TotalCharges                float64
SubscriptionType             object
PaymentMethod                object
PaperlessBilling             object
ContentType                  object
MultiDeviceAccess            object
DeviceRegistered             object
ViewingHoursPerWeek         float64
AverageViewingDuration      float64
ContentDownloadsPerMonth      int64
GenrePreference              object
UserRating                  float64
SupportTicketsPerMonth        int64
Gender                       object
WatchlistSize                 int64
ParentalControl              object
SubtitlesEnabled             object
CustomerID                   object
Churn                         int64
dtype: object

In [37]:
df.describe()

,AccountAge,MonthlyCharges,TotalCharges,ViewingHoursPerWeek,AverageViewingDuration,ContentDownloadsPerMonth,UserRating,SupportTicketsPerMonth,WatchlistSize,Churn
count,243787.000000,243787.000000,243787.000000,243787.000000,243787.000000,243787.000000,243787.000000,243787.000000,243787.000000,243787.000000
mean,60.083758,12.490695,750.741017,20.502179,92.264061,24.503513,3.002713,4.504186,12.018508,0.181232
std,34.285143,4.327615,523.073273,11.243753,50.505243,14.421174,1.155259,2.872548,7.193034,0.385211
min,1.000000,4.990062,4.991154,1.000065,5.000547,0.000000,1.000007,0.000000,0.000000,0.000000
25%,30.000000,8.738543,329.147027,10.763953,48.382395,12.000000,2.000853,2.000000,6.000000,0.000000
50%,60.000000,12.495555,649.878487,20.523116,92.249992,24.000000,3.002261,4.000000,12.000000,0.000000
75%,90.000000,16.238160,1089.317362,30.219396,135.908048,37.000000,4.002157,7.000000,18.000000,0.000000
max,119.000000,19.989957,2378.723844,39.999723,179.999275,49.000000,4.999989,9.000000,24.000000,1.000000

In [38]:
df.describe(include="object")

,SubscriptionType,PaymentMethod,PaperlessBilling,ContentType,MultiDeviceAccess,DeviceRegistered,GenrePreference,Gender,ParentalControl,SubtitlesEnabled,CustomerID
count,243787,243787,243787,243787,243787,243787,243787,243787,243787,243787,243787
unique,3,4,2,3,2,4,5,2,2,2,243787
top,Standard,Electronic check,No,Both,No,Computer,Comedy,Female,Yes,Yes,A6IN701VRY
freq,81920,61313,121980,81737,122035,61147,49060,121930,122085,122180,1

In [39]:
df.nunique()

AccountAge                     119
MonthlyCharges              243787
TotalCharges                243787
SubscriptionType                 3
PaymentMethod                    4
PaperlessBilling                 2
ContentType                      3
MultiDeviceAccess                2
DeviceRegistered                 4
ViewingHoursPerWeek         243787
AverageViewingDuration      243787
ContentDownloadsPerMonth        50
GenrePreference                  5
UserRating                  243787
SupportTicketsPerMonth          10
Gender                           2
WatchlistSize                   25
ParentalControl                  2
SubtitlesEnabled                 2
CustomerID                  243787
Churn                            2
dtype: int64

# PHASE 2 — Data Quality Analysis

   ### Missing Values
1. how many missing values are present?
2. Which column has the most missing values?
3. What percentage of each column is missing?
4. Are missing values concentrated in important columns?
5. Is missingness random?
6. Should missing values be deleted or imputed?
7. What is the best imputation strategy?

### Duplicate Data

8. Are duplicate rows present?
9. How many duplicates are present?
10. Are duplicates exact duplicates?
11. Should duplicates be removed?

### Incorrect Data
12. Are there impossible values?
13. Are there negative values where they shouldn't exist?
14. Are there spelling inconsistencies?
15. Are categories written differently?
16. Are there unexpected data types?
17. Are there invalid dates?
18. Are there suspicious zero values?

In [40]:
df.isnull().sum()

AccountAge                  0
MonthlyCharges              0
TotalCharges                0
SubscriptionType            0
PaymentMethod               0
PaperlessBilling            0
ContentType                 0
MultiDeviceAccess           0
DeviceRegistered            0
ViewingHoursPerWeek         0
AverageViewingDuration      0
ContentDownloadsPerMonth    0
GenrePreference             0
UserRating                  0
SupportTicketsPerMonth      0
Gender                      0
WatchlistSize               0
ParentalControl             0
SubtitlesEnabled            0
CustomerID                  0
Churn                       0
dtype: int64

In [41]:
df.isnull().sum()

(df.isnull().sum() / len(df)) * 100

AccountAge                  0.0
MonthlyCharges              0.0
TotalCharges                0.0
SubscriptionType            0.0
PaymentMethod               0.0
PaperlessBilling            0.0
ContentType                 0.0
MultiDeviceAccess           0.0
DeviceRegistered            0.0
ViewingHoursPerWeek         0.0
AverageViewingDuration      0.0
ContentDownloadsPerMonth    0.0
GenrePreference             0.0
UserRating                  0.0
SupportTicketsPerMonth      0.0
Gender                      0.0
WatchlistSize               0.0
ParentalControl             0.0
SubtitlesEnabled            0.0
CustomerID                  0.0
Churn                       0.0
dtype: float64

In [42]:
df.duplicated().sum()

np.int64(0)

# PHASE 3 — Univariate Analysis

 ### Numerical Variables 
1. What is the distribution of the variable?
2. What is the mean?
3. What is the median?
4. What is the minimum?
5. What is the maximum?
6. What is the standard deviation?
7. What are Q1 and Q3?
8. Is the distribution normal?
9. Is it right-skewed?
10. Is it left-skewed?
11. Are there outliers?
12. What percentage of observations are extreme?

# PHASE 4 — Categorical Analysis
1. How many categories exist?
2. Which category is most common?
3. Which category is least common?
4. What percentage belongs to each category?
5. Is the categorical variable balanced?
6. Are there rare categories?

# PHASE 5 — Target Variable Analysis
1. What is the target variable?
2. What is the target distribution?
3. Is the target balanced?
4. What percentage belongs to each target class?
5. Are there more positive or negative cases?
6. Is there class imbalance?
7. Does the target contain missing values?
8. Does the target contain unexpected values?

# PHASE 6 — Bivariate Analysis
1. Is there a relationship between X and Y?
2. Is the relationship positive?
3. Is the relationship negative?
4. Is the relationship linear?
5. Are there unusual observations?
6. Which numerical variables are strongly related?

# PHASE 7 — Numerical vs Target

1. Does age affect the target?
2. Does income affect the target?
3. Does tenure affect the target?
4. Does spending affect the target?
5. Does account balance affect the target?
6. Do customers with higher values have higher target probability?
7. Do customers with lower values have higher target probability?
8. Is the median different between groups?
9. Is the spread different?
10. Are there outliers?
11. Which group has higher values?

# PHASE 8 — Categorical vs Target
1. Does gender affect the target?
2. Does location affect the target?
3. Does marital status affect the target?
4. Does occupation affect the target?
5. Does education affect the target?
6. Does customer type affect the target?
7. Does payment method affect the target?
8. Does subscription type affect the target?
9. Does contract type affect the target?

# PHASE 9 — Multivariate Analysis
1. How does X affect Y for different categories?
2. Does the relationship change between groups?
3. Which variables jointly influence the target?
4. Are there interaction effects?
5. Are some groups behaving differently?

# PHASE 10 — Correlation Analysis
1. Which numerical variables are correlated?
2. Which variables have strong positive correlation?
3. Which variables have strong negative correlation?
4. Are there highly correlated features?
5. Could multicollinearity be a problem?
6. Is the target correlated with any numerical feature?

# PHASE 11 — Outlier Analysis
1. Which variables contain outliers?
2. How many outliers exist?
3. Are outliers genuine or data errors?
4. Which method should be used to detect them?
5. Do outliers affect the mean?
6. Do outliers affect the model?
7. Should outliers be removed, capped, or retained?

# PHASE 12 — Distribution Analysis
1. Is the feature normally distributed?
2. Is it skewed?
3. What is the skewness?
4. What is the kurtosis?
5. Does the feature require transformation?
6. Is log transformation useful?

# PHASE 13 — Feature vs Feature Questions
1. Which feature has the strongest relationship with the target?
2. Which feature has the weakest relationship?
3. Are there redundant features?
4. Are two columns essentially measuring the same thing?
5. Are there highly correlated features?
6. Can some features be removed?

# PHASE 14 — Group Analysis
1. Which group has the highest average value?
2. Which group has the lowest average value?
3. Which group has the highest target rate?
4. Which group has the lowest target rate?
5. How does the average change across categories?
6. How does the median change across categories?

# PHASE 15 — Time-Series EDA
1. How does the variable change over time?
2. What is the monthly trend?
3. What is the yearly trend?
4. Which month has the highest sales?
5. Which month has the lowest sales?
6. Is there seasonality?
7. Is there a growth trend?
8. Are there unusual spikes?
9. Are there unusual drops?
10. Which day/week/month performs best?

# PHASE 16 — Geographic EDA
1. Which location has the highest value?
2. Which location has the lowest value?
3. Does location affect the target?
4. Which city has the highest churn?
5. Which state has the highest sales?
6. Are there geographical patterns?
7. Are some locations outliers?

# PHASE 17 — Advanced EDA
1Are there highly correlated features?
2. Is there multicollinearity?

3. Is the dataset imbalanced?

4. are there data leakage variables?

5. Are there suspicious features that reveal the target?

6. Are there constant features?

7. Are there near-zero variance features?

8. Are there high-cardinality features?

9. Are there categorical variables requiring encoding?

10. Are transformations required?

11. Are there variables that should be dropped?

12. Which features appear most useful for ML?